name: staging

on:
  pull_request:
    branches:
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install
        run: npm install
      - name: ci
        run: npm run ci
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REACT_APP_PAYPAL_CLIENT_ID: ${{ secrets.REACT_APP_PAYPAL_CLIENT_ID }}
          REACT_APP_STRIPE_PUB: ${{ secrets.REACT_APP_STRIPE_PUB }}
          REACT_APP_DRIFT_ID: ${{ secrets.REACT_APP_DRIFT_ID }}
          REACT_APP_LOG_ROCKET_ID: ${{ secrets.REACT_APP_LOG_ROCKET_ID }}
          REACT_APP_GOOGLE_API_KEY: ${{ secrets.REACT_APP_GOOGLE_API_KEY }}
          REACT_APP_GOOGLE_TAG_MANAGER_ID: ${{ secrets.REACT_APP_GOOGLE_TAG_MANAGER_ID }}
          REACT_APP_GOOGLE_AD_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_AD_CLIENT_ID }}
          REACT_APP_FIREBASE_CONFIG_API_KEY: ${{ secrets.REACT_APP_FIREBASE_CONFIG_API_KEY }}
          REACT_APP_FIREBASE_CONFIG_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_CONFIG_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_CONFIG_DATABASE_URL: ${{ secrets.REACT_APP_FIREBASE_CONFIG_DATABASE_URL }}
          REACT_APP_FIREBASE_CONFIG_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_CONFIG_PROJECT_ID }}
          REACT_APP_FIREBASE_CONFIG_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_CONFIG_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_CONFIG_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_CONFIG_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_CONFIG_APP_ID: ${{ secrets.REACT_APP_FIREBASE_CONFIG_APP_ID }}
          REACT_APP_ALGOLIA_APP_ID: ${{ secrets.REACT_APP_ALGOLIA_APP_ID }}
          REACT_APP_ALGOLIA_ADMIN_KEY: ${{ secrets.REACT_APP_ALGOLIA_ADMIN_KEY }}
